### PR TITLE
Various scope adjustments to ST Terraform syntax

### PR DESCRIPTION
**Pull request by FichteFoll**
Trying out the syntax for the first time, I couldn't help but notice that several wrong colors were being used to highlight text, which was caused by questionable, non-standard or outdated scope names.

The commits included in this PR should mostly stand on their own, i.e. I can be cherry-picked or omitted if desired, though I stand by each change being an improvement.

~~Note that 843b9bf requires ST4 (but can also just be omitted).~~ Edit: [dropped the commit](https://github.com/alexlouden/Terraform.tmLanguage/compare/1fcfe3e95278432659874ea965d049579c5ba54f..c0942a3e0aed0ff5466fc656bdad84cd76bf04ec)

### CODE REVIEW

**Comment by FichteFoll** [comment]
Also, in case you're not interested in maintaining this repo anymore, we could also adopt it into the [SublimeText](https://github.com/SublimeText/) org, where we have several people capable of merging pull requests that are also active Sublime Text users.

**Comment by FichteFoll** [comment]
I also noticed that some of the punctuation scope changes have actually been like this before but were reverted later in a680585ae7b8fd2d710deb743eadd059e593c3db and e895f03bcc5bf581e2b0923c435cb54199ca5245. Since the punctuation scopes are indeed the standardized scope names and have been in use by the default packages, I don't think these arguments hold anymore (if they ever did).

**Comment by FichteFoll** [comment]
I also dropped the commit that uses `extends` because that also requires ST4 and simplified the tfvars tests a lot, which I totally didn't notice. I just didn't see the point in maintaining two basically identical test files for the basically identical syntax.

**Comment by michaelblyons** [comment]
> Also, in case you're not interested in maintaining this repo anymore, we could also adopt it into the [SublimeText](https://github.com/SublimeText/) org, where we have several people capable of merging pull requests that are also active Sublime Text users.

In this time of supply chain risk, it's worth making sure that the claims are true regarding package transfer, but FF is legitimate and so is the GitHub org in question.

**Pull request merged**
